import { storage } from "./storage";
import type { InsertChannel } from "@shared/schema";

const seedChannels: InsertChannel[] = [
  {
    name: "India vs Pakistan - 2007/08 ODI Classic",
    description: "Full highlights of the thrilling 4th ODI between India and Pakistan from the 2007-08 series. A classic encounter featuring stellar batting and bowling performances.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-live-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9dj9mo?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 2850000,
    language: "English",
    country: "Pakistan",
    rating: "4.9",
  },
  {
    name: "India vs Pakistan - Pepsi Cup 2005",
    description: "Extended highlights of the 6th ODI from the Pepsi Cup 2005 series between India and Pakistan. Over 100 minutes of classic cricket action.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-live-2.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9n9226?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1920000,
    language: "English",
    country: "Pakistan",
    rating: "4.8",
  },
  {
    name: "India vs Pakistan - 1984 ODI at Quetta",
    description: "Historic 1st ODI match highlights between India and Pakistan at Quetta from 1984. A rare piece of cricket history with extended 2-hour coverage.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x2glrvv?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1340000,
    language: "English",
    country: "Pakistan",
    rating: "4.7",
  },
  {
    name: "Pakistan vs India - Champions Trophy 2017",
    description: "Pakistan vs India from the ICC Champions Trophy 2017. Line of Cricket brings you complete coverage of this iconic tournament clash.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-live-3.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x5r1azq?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 3560000,
    language: "English",
    country: "England",
    rating: "4.9",
  },
  {
    name: "India vs Australia - 2003/04 VB Series",
    description: "Full highlights of Australia vs India, 1st Final of the 2003/04 VB Series at Melbourne. A thrilling ODI final between two cricket powerhouses.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-highlights-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x99qm0g?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1670000,
    language: "English",
    country: "Australia",
    rating: "4.8",
  },
  {
    name: "India vs West Indies - World Cup 1996",
    description: "Full highlights from the 1996 Cricket World Cup match between India and West Indies. One of the most memorable World Cup encounters.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-live-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9vsxr2?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 2100000,
    language: "English",
    country: "India",
    rating: "4.8",
  },
  {
    name: "Ashes 2005 - 4th Test Warm-Up Archive",
    description: "England Cricket archive - Ashes warm-up match from the legendary 2005 series. Full extended highlights from one of the greatest Ashes series ever.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-training-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9brf6m?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 890000,
    language: "English",
    country: "England",
    rating: "4.7",
  },
  {
    name: "Ashes 2005 - 5th Test The Oval",
    description: "The greatest Ashes series finale! 5th Test at The Oval from the legendary 2005 Ashes. England regain the urn after 16 years.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-live-2.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9bruz2?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1230000,
    language: "English",
    country: "England",
    rating: "4.9",
  },
  {
    name: "Ashes 2009 - 2nd Test at Lord's",
    description: "Complete highlights of England vs Australia 2nd Test at Lord's from the 2009 Ashes. The home of cricket hosts another Ashes classic.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-live-3.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8e8mni?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 780000,
    language: "English",
    country: "England",
    rating: "4.6",
  },
  {
    name: "Ashes 2019 - 3rd Test at Leeds",
    description: "Ben Stokes' miracle at Headingley! Full highlights of England vs Australia 3rd Test from the 2019 Ashes. One of the greatest innings in cricket history.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-highlights-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9lz4dq?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 2450000,
    language: "English",
    country: "England",
    rating: "4.9",
  },
  {
    name: "1981 Ashes - 1st Test Nottingham",
    description: "Classic 1981 Ashes - England vs Australia 1st Test at Nottingham. Part of the legendary Botham's Ashes series.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9wdy90?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 560000,
    language: "English",
    country: "England",
    rating: "4.5",
  },
  {
    name: "England vs Australia 2001 - Lord's Test",
    description: "Full highlights of England vs Australia 2nd Test at Lord's from the 2001 Ashes series. Classic cricket at the home of cricket.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-analysis-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9546us?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 670000,
    language: "English",
    country: "England",
    rating: "4.5",
  },
  {
    name: "South Africa vs India 1997 - Sachin's 169",
    description: "Sachin Tendulkar's magnificent 169 and Azharuddin's 115 in the 2nd Test at Cape Town, 1997. Two legendary innings in one unforgettable match.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-live-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9co5fs?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1890000,
    language: "English",
    country: "South Africa",
    rating: "4.9",
  },
  {
    name: "India vs Pakistan 2006 - 1st Test Lahore",
    description: "Full HD highlights of the 1st Test between India and Pakistan at Lahore from 2006. A thrilling Test match in the great rivalry.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-live-2.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9td1pi?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1560000,
    language: "English",
    country: "Pakistan",
    rating: "4.8",
  },
  {
    name: "NatWest Series 2005 - ENG vs BAN",
    description: "England vs Bangladesh 4th Match at Nottingham from the NatWest Series 2005. Full highlights of an exciting ODI encounter.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-news-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9bxiek?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 430000,
    language: "English",
    country: "England",
    rating: "4.3",
  },
  {
    name: "1985 World Championship - IND vs PAK",
    description: "Highlights from the 1985 World Championship of Cricket group match between India and Pakistan. A golden era of cricket competition.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x2xhmx4?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 780000,
    language: "English",
    country: "Australia",
    rating: "4.6",
  },
  {
    name: "T20 World Cup 2026 - NEP vs WI Preview",
    description: "Nepal vs West Indies T20 World Cup 2026 preview and analysis. Super 8 vs survival battle in Mumbai - who will win?",
    category: "News",
    thumbnailUrl: "/images/channel-live-3.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/xa01xv0?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: true,
    viewers: 1450000,
    language: "English",
    country: "India",
    rating: "4.7",
  },
  {
    name: "IND vs PAK T20 WC - Match Day Analysis",
    description: "India vs Pakistan T20 World Cup 2026 match analysis. Will rain play spoilsport? ICC rules explained and tactical breakdown.",
    category: "News",
    thumbnailUrl: "/images/channel-analysis-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/xa01x3g?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: true,
    viewers: 5200000,
    language: "Hindi",
    country: "India",
    rating: "4.9",
  },
  {
    name: "Har Lamha Purjosh - T20 WC Show",
    description: "Har Lamha Purjosh with Shoaib Malik and Yasir Hussain. In-depth T20 World Cup 2026 analysis and entertainment show.",
    category: "News",
    thumbnailUrl: "/images/channel-news-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/xa00sxc?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 920000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.6",
  },
  {
    name: "ENG vs SCO - T20 World Cup 2026",
    description: "England vs Scotland T20 World Cup 2026 highlights. England stay alive with a convincing 152-127 victory.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/xa0018g?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 670000,
    language: "English",
    country: "England",
    rating: "4.5",
  },
  {
    name: "NZ vs SA T20 Highlights",
    description: "New Zealand vs South Africa T20 highlights. Markram powers South Africa to crush New Zealand in a dominant display.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-highlights-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/xa01wp2?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 540000,
    language: "English",
    country: "South Africa",
    rating: "4.4",
  },
  {
    name: "IND vs PAK T20 WC - Expert Preview",
    description: "India has the edge but Pakistan will be tough - Kapugedera shares expert analysis ahead of the T20 World Cup 2026 blockbuster clash.",
    category: "News",
    thumbnailUrl: "/images/channel-analysis-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zzueo?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: true,
    viewers: 3400000,
    language: "English",
    country: "Sri Lanka",
    rating: "4.8",
  },
  {
    name: "India vs Pakistan - Rain Update",
    description: "Rain set to recast strategy of spin over pace at India vs Pakistan T20 World Cup match. Live weather and pitch report updates.",
    category: "News",
    thumbnailUrl: "/images/channel-news-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/xa01sx2?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: true,
    viewers: 2100000,
    language: "English",
    country: "Sri Lanka",
    rating: "4.6",
  },
  {
    name: "IND vs PAK - Political Analysis",
    description: "Khel ya siyasat? What will happen in Colombo? In-depth discussion about the India vs Pakistan T20 World Cup 2026 clash beyond cricket.",
    category: "News",
    thumbnailUrl: "/images/channel-live-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/xa01twa?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: true,
    viewers: 1780000,
    language: "Hindi",
    country: "India",
    rating: "4.5",
  },
  {
    name: "Richie Benaud - 1993 Ashes Special",
    description: "The legendary Richie Benaud presents his 1993 Ashes Cricket Special. Nearly 2 hours of classic cricket storytelling from the master commentator.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-training-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9o65ui?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 450000,
    language: "English",
    country: "Australia",
    rating: "4.7",
  },
  {
    name: "1985 Ashes - ENG vs AUS 4th Test",
    description: "Full highlights of England vs Australia 4th Test at Manchester from the 1985 Ashes series. Classic Test cricket from the mid-80s.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-live-3.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9vmx5e?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 340000,
    language: "English",
    country: "England",
    rating: "4.4",
  },
  {
    name: "1998-99 Ashes Review - All Five Tests",
    description: "Complete review of all five Tests from the 1998-99 Ashes series. Over an hour of comprehensive analysis and highlights.",
    category: "Test Cricket",
    thumbnailUrl: "/images/channel-analysis-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8xcqos?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 290000,
    language: "English",
    country: "Australia",
    rating: "4.3",
  },
  {
    name: "Sri Lanka vs Australia - Champions Trophy",
    description: "Sri Lanka vs Australia 2nd Semi-Final at Colombo from the 2002 ICC Champions Trophy. Full match highlights of a thrilling knockout game.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-highlights-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9dy0xu?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 560000,
    language: "English",
    country: "Sri Lanka",
    rating: "4.5",
  },
  {
    name: "1996 Titan Cup - IND vs AUS at Mohali",
    description: "India vs Australia 9th Match at Mohali from the 1996 Titan Cup. Over 80 minutes of classic limited-overs cricket action.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9gqpfq?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 720000,
    language: "English",
    country: "India",
    rating: "4.6",
  },
  {
    name: "Afghanistan vs Pakistan - 2nd ODI",
    description: "Afghanistan vs Pakistan full match highlights from the 2nd ODI. Complete coverage of this exciting encounter between cricket neighbors.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-live-2.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8nlhp3?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 890000,
    language: "English",
    country: "Pakistan",
    rating: "4.4",
  },
  {
    name: "IND vs PAK - Public Reaction T20 WC",
    description: "India vs Pakistan T20 World Cup 2026 - Public reaction from across Pakistan. What are fans saying about Team India ahead of the big match?",
    category: "News",
    thumbnailUrl: "/images/channel-news-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zzk74?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1340000,
    language: "Hindi",
    country: "Pakistan",
    rating: "4.3",
  },
  {
    name: "Asia Cup 2025 Final - IND vs PAK",
    description: "India's historic victory in the Asia Cup 2025 Final against Pakistan. Celebrations and highlights from this dramatic encounter.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-live-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9rdfmo?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 4200000,
    language: "Telugu",
    country: "India",
    rating: "4.8",
  },
  {
    name: "India vs Australia - Match Highlights",
    description: "India vs Australia full match highlights. An exciting clash between two of cricket's biggest rivals.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-highlights-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9y3gm6?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1560000,
    language: "English",
    country: "Australia",
    rating: "4.7",
  },
  {
    name: "IND vs PAK T20 WC - Hanumankind Show",
    description: "PM Modi's favorite artist Hanumankind to perform at IND vs PAK T20 World Cup 2026. Pre-match entertainment and coverage.",
    category: "News",
    thumbnailUrl: "/images/channel-live-3.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zzx2y?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: true,
    viewers: 980000,
    language: "Hindi",
    country: "India",
    rating: "4.2",
  },
  {
    name: "Har Lamha Purjosh - Shoaib Malik Show",
    description: "Har Lamha Purjosh with Shoaib Malik and Mizna Waqas. T20 World Cup 2026 analysis, predictions, and cricket entertainment from Pakistan's top sports show.",
    category: "News",
    thumbnailUrl: "/images/channel-analysis-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zy1m6?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: true,
    viewers: 1890000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.7",
  },
  {
    name: "Har Lamha Purjosh - Hassan Ahmed",
    description: "Har Lamha Purjosh with Shoaib Malik and Hassan Ahmed. T20 World Cup 2026 special edition with celebrity guest analysis and match previews.",
    category: "News",
    thumbnailUrl: "/images/channel-news-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zr4yk?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1120000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.6",
  },
  {
    name: "Har Lamha Purjosh - T20 WC Special",
    description: "Har Lamha Purjosh with Shoaib Malik. Extended T20 World Cup 2026 analysis show featuring expert predictions and team breakdowns.",
    category: "News",
    thumbnailUrl: "/images/channel-live-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zo4n6?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 980000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.5",
  },
  {
    name: "Har Lamha Purjosh - Ali Rehman Khan",
    description: "Har Lamha Purjosh with Shoaib Malik and Ali Rehman Khan. Cricket meets entertainment as celebrities discuss T20 World Cup 2026 excitement.",
    category: "News",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zl0bc?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 870000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.5",
  },
  {
    name: "Har Lamha Purjosh - Zahid Ahmed",
    description: "Har Lamha Purjosh with Shoaib Malik and Zahid Ahmed. T20 World Cup 2026 cricket chat with one of Pakistan's most popular TV actors.",
    category: "News",
    thumbnailUrl: "/images/channel-analysis-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zifkq?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 760000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.4",
  },
  {
    name: "Har Lamha Purjosh - Maryam Noor",
    description: "Har Lamha Purjosh with Shoaib Malik and Maryam Noor. Pakistani celebrities share their love for cricket and T20 World Cup predictions.",
    category: "News",
    thumbnailUrl: "/images/channel-news-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x9zgj7s?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 650000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.4",
  },
  {
    name: "The Pavilion - PSL9 Expert Analysis",
    description: "The Pavilion brings expert post-match analysis from PSL 9. Multan Sultans vs Lahore Qalandars breakdown with former cricketers and analysts.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-highlights-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8tghz2?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1340000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.7",
  },
  {
    name: "The Pavilion - KK vs LQ Preview",
    description: "The Pavilion pre-match analysis for Karachi Kings vs Lahore Qalandars. PSL 9 expert discussion with former cricketers breaking down team strategies.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8u4nkq?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 890000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.5",
  },
  {
    name: "The Pavilion - MS vs PZ Preview",
    description: "The Pavilion pre-match expert analysis for Multan Sultans vs Peshawar Zalmi. PSL 9 tactical breakdown and predictions from the panel.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-live-2.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8twbl6?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 780000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.5",
  },
  {
    name: "The Pavilion - PZ vs MS Analysis",
    description: "The Pavilion pre-match analysis for Peshawar Zalmi vs Multan Sultans. Expert panel discusses PSL 9 playoff scenarios and key matchups.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-analysis-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8ufthq?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 670000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.4",
  },
  {
    name: "Har Lamha Purjosh - PSL Special",
    description: "Har Lamha Purjosh with Waseem Badami. Extended PSL 9 special edition with comprehensive coverage and expert analysis of the Pakistan Super League.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-live-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x8uu7x4?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 1560000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.8",
  },
  {
    name: "PSL 2017 Closing Ceremony",
    description: "Complete coverage of the Pakistan Super League 2017 closing ceremony. The grand finale celebrating Pakistani cricket and entertainment.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-highlights-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x5dy7xb?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 2100000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.6",
  },
  {
    name: "PAK vs NZ Special Transmission",
    description: "Pakistan vs New Zealand special cricket transmission with full match analysis, expert commentary, and post-match discussion.",
    category: "Highlights",
    thumbnailUrl: "/images/channel-live-3.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x848wnr?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 560000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.3",
  },
  {
    name: "Multan Sultans vs Peshawar Zalmi",
    description: "PSL 2020 highlights - Multan Sultans vs Peshawar Zalmi. Pakistan Super League action featuring the best T20 cricket talent.",
    category: "T20 League",
    thumbnailUrl: "/images/channel-t20-1.jpg",
    streamUrl: "https://www.dailymotion.com/embed/video/x7s9gj0?autoplay=1&queue-enable=0&ui-logo=0",
    isLive: false,
    viewers: 430000,
    language: "Urdu",
    country: "Pakistan",
    rating: "4.3",
  },
];

export async function seedDatabase() {
  try {
    const count = await storage.getChannelCount();
    if (count > 0) {
      console.log(`Database already has ${count} channels, skipping seed.`);
      return;
    }

    console.log("Seeding database with cricket channels...");
    for (const channel of seedChannels) {
      await storage.createChannel(channel);
    }
    console.log(`Seeded ${seedChannels.length} channels successfully.`);
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
